runtime: nodejs10
env_variables:
  # NETWORKS: instagram,facebook,twitter,google,skype
  # REDIS_URL: redis://username:password@uri:port/db
  # MEMCACHE_URL: memcache:11211
  # TTL_PROFILE_PICTURE: 3600000
  # LIMIT_REFERER: ^https://domain.example.org/
  # LOG_FORMAT: combined
